### ISSUE TITLE
AE2 Cables and Cable Facades broken textures

### ISSUE THREAD

**Issue by TheOnlyPhoenix** [F32Organization/Faithful32-1.12.2#175]
The textures for all types of AE2 cables are broken, as well as SOME of the facades, ones made with modded blocks, like chisel. This is really annoying, as you cannot directly see how many channels there are. I am playing with Optifine if that makes a difference.
![2020-05-09_23 24 58](https://user-images.githubusercontent.com/54004241/81485339-97319400-924c-11ea-9d85-9f2d7b418dea.png)

**Comment by Bernasss12** [comment]
I'm not too sure if OptiFine does or doesn't make a difference, I also am not sure about the conduit problems, what I do know is that depending on which version of Chisel you have installed there is nothing we can do to fix those facade textures since the mod has an new resource folder structure and that has been updated. Breaking the older versions.

**Comment by Officialy** [comment]
I figured this one out recently. If Anisotropic filtering is on this will happen. If it's already off then this is something different

**Comment by TheOnlyPhoenix** [comment]
Anisotropic filtering is off...

**Comment by StefanTT** [comment]
I had it myself and it was reported on F32 several times in the past years.
Up to now this was never the fault of the texture pack.
Usually a Minecraft restart fixes the problem.
