### ISSUE TITLE
Resolve multiple conflicts with identically named package on curse.com

### ISSUE THREAD

**Issue by midorlo** [F32Organization/Faithful32-1.12.2#27]
Given the following existences

[Faithful32 on Curse.com](https://www.curseforge.com/minecraft/texture-packs/faithful-32x), updated 2017-11-21, Owned by: [xMrVizzy](https://www.curseforge.com/members/xMrVizzy), License:  All rights reserved
[Modded-Faithful on Curse.com](https://www.curseforge.com/minecraft/texture-packs/modded-faithful), updated 2017-10-18, Owned by: [xMrVizzy](https://www.curseforge.com/members/xMrVizzy), License:  All rights reserved

I assume that there may be topics resolve with said user in terms of license, ownership, cited contributors and maybe also about continious deployment systems for curse.com.

**Comment by Evolution0** [comment]
You're mistaken, for the first @xMrVizzy took over for Vattic basically which is why they have a Patreon now, Vattic stopped working on Faithful (Which is what Faithful32 is based on) after 1.8.

The second _is_ based on Faithful32 but I'm quite sure the rest of the contributors are aware of it or at least I remember some discussion on this back in the day, its not a 1:1 copy of the repo here and I believe is has a lot of @xMrVizzy separate work in it now. The contributors list is also properly linked in the description.

As for Licensing, I'm of the belief that Curse applies that license if you don't specify one when creating the project.

**Comment by StefanTT** [comment]
AFAIK the Faithful packages on Curse are xMrVizzy's own work, possibly derived from Vattic's original with his permission. Anyways, as far as I know there are no licensing problems as he does not copy stuff from here. It's rather the other way around, some of his work is also in this repository (with his permission).

**Comment by xMrVizzy** [comment]
Hello! Of course I have permission from Vattic! And now, as you might have noticed, since version 1.9, I have started to completely redraw most textures from scratch, because most of them were poorly designed! 👍

**Comment by StefanTT** [comment]
Thank you for the clarification :-)
